version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hello-opencloud:
    lang: node12
    handler: ./hello-opencloud
    image: gargshivam1997/hello-opencloud:latest

